import { nanoid } from "nanoid";

export default {
  namespaced: true,

  state: {
    forms: [
      {
        id: "45e4c0a7-a038-4ada-be60-c42ba7799a86",
        name: "Oloo",
        description:
          "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
        status: "ARCHIVED",
        isFavourite: false,
        lastModified: "2021-09-25T13:30:15Z",
        layout: "CARD",
        panels: [],
        submissions: 52,
      },
      {
        id: "561b6ff3-6123-4790-8da0-7669ae7f5823",
        name: "Meevee",
        description:
          "Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-11-11T05:55:28Z",
        layout: "CARD",
        panels: [],
        submissions: 65,
      },
      {
        id: "fa529318-ecfa-47ff-9ad9-6277c5fb41ca",
        name: "Zooxo",
        description:
          "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-09-14T09:56:59Z",
        layout: "CARD",
        panels: [],
        submissions: 16,
      },
      {
        id: "959439d4-17ab-465c-ba82-a49cc5b416cf",
        name: "Yakitri",
        description:
          "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-08-11T11:12:22Z",
        layout: "CARD",
        panels: [],
        submissions: 47,
      },
      {
        id: "a75cd9c1-7b46-4773-97d5-6649d7bbd30b",
        name: "Mynte",
        description:
          "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-08-28T01:01:57Z",
        layout: "CARD",
        panels: [],
        submissions: 92,
      },
      {
        id: "45aeb91e-9a93-4b35-879c-f8672383ef95",
        name: "Feedmix",
        description:
          "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
        status: "ARCHIVED",
        isFavourite: false,
        lastModified: "2021-09-18T20:41:41Z",
        layout: "CARD",
        panels: [],
        submissions: 2,
      },
      {
        id: "10159051-e545-48fc-840c-e73d94255827",
        name: "Realcube",
        description: "In congue. Etiam justo. Etiam pretium iaculis justo.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-11-16T20:36:53Z",
        layout: "CARD",
        panels: [],
        submissions: 10,
      },
      {
        id: "28c0c47d-a14f-4e5f-95a2-1c0bdac4eabb",
        name: "Oba",
        description:
          "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-09-20T15:17:57Z",
        layout: "CARD",
        panels: [],
        submissions: 86,
      },
      {
        id: "4412805a-496e-4b35-bb20-47b4b3ccc8af",
        name: "Voonte",
        description:
          "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-11-24T22:34:05Z",
        layout: "CARD",
        panels: [],
        submissions: 3,
      },
      {
        id: "96f195cc-f2f0-437d-b87c-53631604df06",
        name: "Photolist",
        description:
          "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-11-04T04:15:37Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 95,
      },
      {
        id: "4d7adda7-3eb9-4430-94d8-0cbdfa056ed4",
        name: "Blogtag",
        description:
          "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
        status: "ARCHIVED",
        isFavourite: false,
        lastModified: "2021-10-10T19:11:50Z",
        layout: "CARD",
        panels: [],
        submissions: 41,
      },
      {
        id: "0dfe971b-aa42-4e37-9420-f826a01b1f35",
        name: "Livetube",
        description:
          "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-08-05T14:09:29Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 70,
      },
      {
        id: "299f9331-69e0-4888-a077-81cedb92067c",
        name: "Dabfeed",
        description:
          "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-10-11T20:22:47Z",
        layout: "CARD",
        panels: [],
        submissions: 38,
      },
      {
        id: "9e64d98b-28ca-4ad5-8015-24144fd0b946",
        name: "Fivechat",
        description: "In congue. Etiam justo. Etiam pretium iaculis justo.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-10-11T07:47:48Z",
        layout: "CARD",
        panels: [],
        submissions: 51,
      },
      {
        id: "e5d81b37-0a3c-41e8-bde4-e9a8c40af5e6",
        name: "Shuffledrive",
        description:
          "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-10-10T10:25:32Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 83,
      },
      {
        id: "1aa2620e-4061-4269-8a6b-363767157a84",
        name: "Browsetype",
        description:
          "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-08-04T17:31:08Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 81,
      },
      {
        id: "ae832ba4-3ce7-4205-b397-2029364f64df",
        name: "Yodel",
        description:
          "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-08-23T13:16:15Z",
        layout: "CARD",
        panels: [],
        submissions: 83,
      },
      {
        id: "8a967183-b1c7-4bc4-afff-92850fd79697",
        name: "Avaveo",
        description:
          "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-09-20T20:03:29Z",
        layout: "CARD",
        panels: [],
        submissions: 47,
      },
      {
        id: "83465e7b-3174-4f3b-84cd-def786a949f6",
        name: "Gevee",
        description:
          "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-11-26T17:37:01Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 79,
      },
      {
        id: "8cf382cb-5839-4897-a54e-4e0b7542964d",
        name: "Livefish",
        description:
          "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
        status: "TRASHED",
        isFavourite: false,
        lastModified: "2021-11-06T05:53:59Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 51,
      },
      {
        id: "df00f863-9884-4dd2-8b64-46979ac79621",
        name: "Tanoodle",
        description:
          "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
        status: "TRASHED",
        isFavourite: false,
        lastModified: "2021-11-17T13:22:10Z",
        layout: "CARD",
        panels: [],
        submissions: 99,
      },
      {
        id: "02411bd4-4576-45d7-bc14-085415ce2035",
        name: "Leexo",
        description:
          "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
        status: "ARCHIVED",
        isFavourite: false,
        lastModified: "2021-10-09T21:43:00Z",
        layout: "CARD",
        panels: [],
        submissions: 51,
      },
      {
        id: "3bf7fd30-a41c-420d-9c98-ded75f752fad",
        name: "Digitube",
        description:
          "Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-08-17T14:00:38Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 99,
      },
      {
        id: "1c1e2a41-f727-4d90-8fd0-2a98e6c3d9a7",
        name: "Babbleset",
        description:
          "Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-10-06T09:43:02Z",
        layout: "CARD",
        panels: [],
        submissions: 11,
      },
      {
        id: "bfeaa4a5-3b4e-4e79-a69b-8d7b2d93e44a",
        name: "Livepath",
        description:
          "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-09-06T15:11:48Z",
        layout: "CARD",
        panels: [],
        submissions: 27,
      },
      {
        id: "2191a228-b89e-4910-945b-78b534feb16c",
        name: "Voonte",
        description:
          "Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-08-22T19:35:51Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 72,
      },
      {
        id: "777dffa7-ff70-494b-aa10-9b4b6bee11d6",
        name: "Eazzy",
        description:
          "Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-11-20T17:20:55Z",
        layout: "CARD",
        panels: [],
        submissions: 64,
      },
      {
        id: "0dc26abc-7d8d-4f13-9d6a-f853aa9e4e5f",
        name: "Realbridge",
        description:
          "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-10-12T23:12:14Z",
        layout: "CARD",
        panels: [],
        submissions: 38,
      },
      {
        id: "0b9fd9f4-b091-4d69-958c-bda7da8dfc04",
        name: "Layo",
        description:
          "Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-11-13T12:17:25Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 16,
      },
      {
        id: "453ebd6a-713f-4041-a2a1-6485da61428c",
        name: "Rhycero",
        description:
          "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
        status: "TRASHED",
        isFavourite: false,
        lastModified: "2021-09-01T09:40:48Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 30,
      },
      {
        id: "2bb1cda0-fb7f-4e67-bff6-0ca624788df5",
        name: "Avaveo",
        description:
          "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-10-18T04:35:55Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 42,
      },
      {
        id: "b83d9254-469a-48ab-901f-af173c0e9293",
        name: "Edgeify",
        description:
          "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-10-05T01:28:29Z",
        layout: "CARD",
        panels: [],
        submissions: 33,
      },
      {
        id: "2448748c-6b4b-42ac-b564-c8ff4862688d",
        name: "Quatz",
        description: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-08-26T23:41:37Z",
        layout: "CARD",
        panels: [],
        submissions: 52,
      },
      {
        id: "17f6a7ae-0ff2-46d7-aebf-92aa8cd49419",
        name: "Quimm",
        description:
          "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        status: "ARCHIVED",
        isFavourite: false,
        lastModified: "2021-10-19T16:01:59Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 16,
      },
      {
        id: "0c7bdc26-97f1-4140-b06f-7d6f0d045d81",
        name: "Thoughtstorm",
        description:
          "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-09-11T01:36:34Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 77,
      },
      {
        id: "aff30c3c-0950-404c-b556-156dcf074eab",
        name: "Browsebug",
        description: "Fusce consequat. Nulla nisl. Nunc nisl.",
        status: "TRASHED",
        isFavourite: false,
        lastModified: "2021-10-12T02:32:34Z",
        layout: "CARD",
        panels: [],
        submissions: 26,
      },
      {
        id: "d92aea5a-3b3d-4197-af5e-ecbb246b16d3",
        name: "Fanoodle",
        description:
          "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-08-17T06:18:34Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 83,
      },
      {
        id: "9a89d7c8-d1c6-48ab-b6aa-3d1576bc3fca",
        name: "Muxo",
        description:
          "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
        status: "TRASHED",
        isFavourite: false,
        lastModified: "2021-09-11T07:03:59Z",
        layout: "CARD",
        panels: [],
        submissions: 74,
      },
      {
        id: "96784aa9-bf97-49c1-b3fc-18b5574d21dd",
        name: "Zoonder",
        description:
          "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-10-16T10:10:29Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 51,
      },
      {
        id: "7e12ab34-6ff1-4672-a5f5-97a7209b154a",
        name: "Reallinks",
        description:
          "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-09-17T10:16:20Z",
        layout: "CARD",
        panels: [],
        submissions: 80,
      },
      {
        id: "b019cc7b-89d8-4259-bdc4-b7009c630e5d",
        name: "Zoomzone",
        description:
          "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-09-09T11:26:48Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 53,
      },
      {
        id: "87540d18-9b48-45ab-9e8f-61a885ecf9ca",
        name: "Fadeo",
        description:
          "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-08-06T00:09:54Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 35,
      },
      {
        id: "2b6ed1b0-c8b9-4957-9aa5-3637a6aa0b55",
        name: "Edgetag",
        description:
          "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-08-23T22:46:51Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 12,
      },
      {
        id: "8faaed4f-3d74-4285-a2bd-b09158a1be6a",
        name: "InnoZ",
        description:
          "Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.",
        status: "ARCHIVED",
        isFavourite: false,
        lastModified: "2021-08-20T07:10:40Z",
        layout: "CARD",
        panels: [],
        submissions: 34,
      },
      {
        id: "6d64da05-755f-4a61-a5ef-71973d20103a",
        name: "Browsebug",
        description:
          "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-10-13T04:52:38Z",
        layout: "CARD",
        panels: [],
        submissions: 29,
      },
      {
        id: "81d8c480-f658-46f2-96ce-068429d6302f",
        name: "Fadeo",
        description:
          "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-09-18T00:05:00Z",
        layout: "CARD",
        panels: [],
        submissions: 40,
      },
      {
        id: "084b4a91-88ef-487a-9f16-8a057c82e9a8",
        name: "Bluezoom",
        description:
          "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
        status: "TRASHED",
        isFavourite: false,
        lastModified: "2021-09-18T08:59:46Z",
        layout: "CARD",
        panels: [],
        submissions: 70,
      },
      {
        id: "9f9e9611-6c3e-477a-8478-ccb04bde9185",
        name: "Tavu",
        description:
          "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-10-28T09:26:26Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 56,
      },
      {
        id: "3a08d206-5ece-4fab-b72e-162da9f68d0a",
        name: "Pixope",
        description:
          "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-11-01T14:00:37Z",
        layout: "CARD",
        panels: [],
        submissions: 44,
      },
      {
        id: "9c254881-c5d9-4358-bb4a-c253c2e2596a",
        name: "Thoughtbeat",
        description:
          "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-08-11T10:35:21Z",
        layout: "CARD",
        panels: [],
        submissions: 92,
      },
      {
        id: "edc35d88-e761-467b-9ef6-7c1eef001ec0",
        name: "Centidel",
        description:
          "Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-09-17T13:58:02Z",
        layout: "CARD",
        panels: [],
        submissions: 17,
      },
      {
        id: "0ed61a5e-58d7-47cd-a864-262829e1a053",
        name: "Twitterwire",
        description: "Fusce consequat. Nulla nisl. Nunc nisl.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-09-05T21:38:45Z",
        layout: "CARD",
        panels: [],
        submissions: 20,
      },
      {
        id: "94e886d4-0156-45b9-8c79-85c36210c794",
        name: "Aimbu",
        description:
          "Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.",
        status: "TRASHED",
        isFavourite: false,
        lastModified: "2021-09-03T08:38:22Z",
        layout: "CARD",
        panels: [],
        submissions: 78,
      },
      {
        id: "3323a2d8-78ef-4e38-b99c-ab09532b5825",
        name: "Zoombox",
        description:
          "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-08-08T19:03:50Z",
        layout: "CARD",
        panels: [],
        submissions: 50,
      },
      {
        id: "d862e4a5-e892-4b27-ab07-adb499eec829",
        name: "Roomm",
        description:
          "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-11-23T00:29:29Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 13,
      },
      {
        id: "eea3ba31-6b84-4709-8afd-0d5bc9f33c3f",
        name: "Chatterbridge",
        description:
          "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-09-15T07:36:09Z",
        layout: "CARD",
        panels: [],
        submissions: 50,
      },
      {
        id: "f890cf48-416a-4ab1-ac9c-898503f2f737",
        name: "BlogXS",
        description:
          "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-09-20T08:34:59Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 92,
      },
      {
        id: "4fcea1d3-1d25-4382-911a-bab42284112c",
        name: "Devcast",
        description:
          "Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.",
        status: "ARCHIVED",
        isFavourite: false,
        lastModified: "2021-08-14T08:21:15Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 27,
      },
      {
        id: "cd4eb057-dc11-405e-a933-d91f2804aa93",
        name: "Chatterbridge",
        description:
          "Phasellus in felis. Donec semper sapien a libero. Nam dui.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-08-17T21:01:07Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 86,
      },
      {
        id: "1b4fd99f-20b4-4067-abd4-3ff54ff8b7f0",
        name: "Eazzy",
        description:
          "Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-09-09T10:01:24Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 29,
      },
      {
        id: "e04fbf4c-e6ec-4797-9dae-03aff7691fd8",
        name: "Devpulse",
        description:
          "Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-08-06T04:15:16Z",
        layout: "CARD",
        panels: [],
        submissions: 71,
      },
      {
        id: "a7ff54b7-818c-4f2d-b0c5-62b331d5bf84",
        name: "Kwinu",
        description:
          "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-10-22T18:44:58Z",
        layout: "CARD",
        panels: [],
        submissions: 13,
      },
      {
        id: "e9600f8d-5dd1-4178-9938-5d41cb153251",
        name: "Skivee",
        description: "Fusce consequat. Nulla nisl. Nunc nisl.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-08-24T06:17:59Z",
        layout: "CARD",
        panels: [],
        submissions: 70,
      },
      {
        id: "392bb461-24a7-4ac9-9c8d-62bb89a4ccdf",
        name: "Zoonoodle",
        description:
          "Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-11-24T05:52:25Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 24,
      },
      {
        id: "cbc9a72e-d035-47d7-959b-7ebd509430e3",
        name: "Fiveclub",
        description:
          "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-09-05T05:53:14Z",
        layout: "CARD",
        panels: [],
        submissions: 59,
      },
      {
        id: "b3445d20-824f-43c6-84d4-8c706f5aa68b",
        name: "Dabvine",
        description:
          "Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-09-03T20:55:03Z",
        layout: "CARD",
        panels: [],
        submissions: 35,
      },
      {
        id: "67f353e7-34c7-463c-9c65-83a5f9d21959",
        name: "Shufflester",
        description:
          "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-09-09T20:24:02Z",
        layout: "CARD",
        panels: [],
        submissions: 64,
      },
      {
        id: "9b7db3c2-722e-4a6c-98fe-3cc0f5701b5a",
        name: "Voomm",
        description:
          "Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.",
        status: "ARCHIVED",
        isFavourite: false,
        lastModified: "2021-10-22T19:18:31Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 38,
      },
      {
        id: "7d29c5cb-9a1e-4bb5-b14f-ca8cc4d417ba",
        name: "Jabbercube",
        description: "Fusce consequat. Nulla nisl. Nunc nisl.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-10-19T13:43:10Z",
        layout: "CARD",
        panels: [],
        submissions: 73,
      },
      {
        id: "aecab1e4-b9db-415a-b62f-213b5f310465",
        name: "Topicblab",
        description:
          "Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-10-09T05:32:16Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 92,
      },
      {
        id: "02a8273e-a6d6-4dbc-ab19-75eba9e6afa6",
        name: "Ozu",
        description: "In congue. Etiam justo. Etiam pretium iaculis justo.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-09-25T21:38:38Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 59,
      },
      {
        id: "a2001b37-1735-4b60-b270-0fbee15fa2f4",
        name: "Avavee",
        description:
          "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-11-09T00:06:56Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 68,
      },
      {
        id: "a32492ab-c5e5-448f-a94f-535c8682a37d",
        name: "Eadel",
        description:
          "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-09-04T08:19:45Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 39,
      },
      {
        id: "3d8b5beb-9e8b-4294-9cb2-11034ce22423",
        name: "Eidel",
        description:
          "Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.",
        status: "ARCHIVED",
        isFavourite: false,
        lastModified: "2021-08-03T23:07:54Z",
        layout: "CARD",
        panels: [],
        submissions: 12,
      },
      {
        id: "f816dfc7-7070-47e2-814f-bbb009e55f67",
        name: "Jetwire",
        description:
          "Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-11-03T09:56:23Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 97,
      },
      {
        id: "d6eeb0f0-3828-4d0f-bcfd-a7ff8a39b4c7",
        name: "Twinder",
        description:
          "Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.",
        status: "ARCHIVED",
        isFavourite: true,
        lastModified: "2021-11-04T08:55:22Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 76,
      },
      {
        id: "1a13b347-4a31-468f-83ca-14cb54419f12",
        name: "Dynabox",
        description:
          "Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-10-31T13:54:58Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 25,
      },
      {
        id: "4823bf9e-e964-4691-85d6-03a3c5c77ff9",
        name: "Tanoodle",
        description:
          "Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-11-16T01:47:50Z",
        layout: "CARD",
        panels: [],
        submissions: 25,
      },
      {
        id: "f3973740-4eb7-4f37-8083-c5a1495f8e37",
        name: "Thoughtblab",
        description:
          "Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-09-19T02:55:13Z",
        layout: "CARD",
        panels: [],
        submissions: 11,
      },
      {
        id: "777cba64-8377-43ff-950a-bdf489c6e84a",
        name: "Skidoo",
        description:
          "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-10-25T09:02:40Z",
        layout: "CARD",
        panels: [],
        submissions: 1,
      },
      {
        id: "b99998db-fdd4-4710-9781-c05c54800f2d",
        name: "Tazz",
        description:
          "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-08-13T00:42:58Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 30,
      },
      {
        id: "207fb1bc-43f5-45e2-b26b-56ada0f3bdb0",
        name: "Feedfish",
        description:
          "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-11-18T12:58:08Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 73,
      },
      {
        id: "8acafad9-7767-48b8-9877-66d47da6cd43",
        name: "Yombu",
        description:
          "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-09-24T06:27:17Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 59,
      },
      {
        id: "7f703aa0-4b5a-4037-a4db-0226ad39a3d6",
        name: "Wikizz",
        description:
          "Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.",
        status: "TRASHED",
        isFavourite: false,
        lastModified: "2021-09-30T01:44:24Z",
        layout: "CARD",
        panels: [],
        submissions: 23,
      },
      {
        id: "fc561e50-f2c8-4d91-9d94-8492d4dc8c7d",
        name: "Kazio",
        description: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-09-05T23:58:27Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 36,
      },
      {
        id: "ad253ba6-e506-4e1d-8e29-357d1da186b4",
        name: "Avavee",
        description:
          "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-09-15T03:58:06Z",
        layout: "CARD",
        panels: [],
        submissions: 28,
      },
      {
        id: "7c9273de-80ca-4cb8-ad83-1f94c5088ca3",
        name: "Dynabox",
        description:
          "Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-10-16T23:18:41Z",
        layout: "CARD",
        panels: [],
        submissions: 45,
      },
      {
        id: "e698bce0-4b5d-40d5-a1ef-e44f84216ec0",
        name: "Trudoo",
        description:
          "Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-08-24T21:28:42Z",
        layout: "CARD",
        panels: [],
        submissions: 56,
      },
      {
        id: "5baa80a8-db05-4313-a89a-914badd776c5",
        name: "Bubbletube",
        description:
          "In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.",
        status: "TRASHED",
        isFavourite: false,
        lastModified: "2021-11-15T03:43:53Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 13,
      },
      {
        id: "dd53c0db-ba0a-4931-9410-3be12e5b4db4",
        name: "Trupe",
        description:
          "In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-11-27T09:38:31Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 39,
      },
      {
        id: "225326d9-6636-47f5-8225-3f92fe62937e",
        name: "Bubblebox",
        description:
          "Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-08-15T04:15:30Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 45,
      },
      {
        id: "5ba9dfc2-4c83-419c-8c5a-0094cc5a13aa",
        name: "Trunyx",
        description:
          "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
        status: "DRAFT",
        isFavourite: true,
        lastModified: "2021-08-23T23:01:51Z",
        layout: "CARD",
        panels: [],
        submissions: 60,
      },
      {
        id: "fcea4a0c-5478-4dec-a941-92fd7312bafe",
        name: "Mydeo",
        description:
          "Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.",
        status: "TRASHED",
        isFavourite: false,
        lastModified: "2021-08-31T11:59:43Z",
        layout: "CARD",
        panels: [],
        submissions: 23,
      },
      {
        id: "915b836c-2eb2-40b5-8997-4372c304880f",
        name: "Blogpad",
        description:
          "Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-09-05T01:55:15Z",
        layout: "CARD",
        panels: [],
        submissions: 63,
      },
      {
        id: "bc7be874-ced0-42b1-acf4-bec3a5c4443d",
        name: "Gabspot",
        description:
          "Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.",
        status: "PUBLISHED",
        isFavourite: false,
        lastModified: "2021-11-05T16:31:48Z",
        layout: "CARD",
        panels: [],
        submissions: 52,
      },
      {
        id: "c5195d0d-196a-42a5-bde7-7499f7254088",
        name: "Quamba",
        description: "Sed ante. Vivamus tortor. Duis mattis egestas metus.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-08-28T08:05:06Z",
        layout: "CARD",
        panels: [],
        submissions: 68,
      },
      {
        id: "d8533b0b-3e97-43ae-ae8a-3352856e4735",
        name: "Brainlounge",
        description:
          "Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.",
        status: "TRASHED",
        isFavourite: true,
        lastModified: "2021-08-14T17:32:18Z",
        layout: "CLASSIC",
        panels: [],
        submissions: 59,
      },
      {
        id: "0afaf3ef-64d5-426c-9619-bdbb3e8f2559",
        name: "Geba",
        description:
          "Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-08-03T20:04:43Z",
        layout: "CARD",
        panels: [],
        submissions: 3,
      },
      {
        id: "9dfaf0ec-51a7-4ebb-89c7-fd9d3759c700",
        name: "Dazzlesphere",
        description:
          "Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.",
        status: "DRAFT",
        isFavourite: false,
        lastModified: "2021-08-13T06:14:38Z",
        layout: "CARD",
        panels: [],
        submissions: 41,
      },
      {
        id: "524c6313-a244-4215-aaf1-60bff617c109",
        name: "Trudoo",
        description:
          "Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.",
        status: "PUBLISHED",
        isFavourite: true,
        lastModified: "2021-11-04T18:19:16Z",
        layout: "CARD",
        panels: [],
        submissions: 89,
      },
    ],
  },

  getters: {
    totalForms(state) {
      return state.forms.length;
    },

    publishedForms(state) {
      return state.forms.filter((form) => form.status === "PUBLISHED").length;
    },

    draftedForms(state) {
      return state.forms.filter((form) => form.status === "DRAFT").length;
    },

    archivedForms(state) {
      return state.forms.filter((form) => form.status === "ARCHIVED").length;
    },

    trashedForms(state) {
      return state.forms.filter((form) => form.status === "TRASHED").length;
    },

    favouriteForms(state) {
      return state.forms.filter((form) => form.isFavourite).length;
    },

    stats(_, getters) {
      return [
        {
          id: nanoid(),
          label: "all",
          count: getters.totalForms,
          icon: "mdi-view-dashboard-outline",
          color: {
            palette: "primary",
            name: "primary",
            rgba: "rgba(72, 73, 161, 0.8)",
          },
        },
        {
          id: nanoid(),
          label: "published",
          count: getters.publishedForms,
          icon: "eva-external-link-outline",
          color: {
            palette: "tertiary",
            name: "tertiary",
            rgba: "rgba(37, 204, 201, 0.8)",
          },
        },
        {
          id: nanoid(),
          label: "drafted",
          count: getters.draftedForms,
          icon: "mdi-text-box-outline",
          color: {
            palette: "secondary",
            name: "secondary",
            rgba: "rgba(249, 119, 103, 0.8)",
          },
        },
        {
          id: nanoid(),
          label: "archived",
          count: getters.archivedForms,
          icon: "eva-archive-outline",
          color: {
            palette: "blue",
            name: "blue-5",
            rgba: "rgba(66, 165, 245, 0.8)",
          },
        },
        {
          id: nanoid(),
          label: "trashed",
          count: getters.trashedForms,
          icon: "eva-trash-2-outline",
          color: {
            palette: "pink",
            name: "pink-5",
            rgba: "rgba(236, 64, 122, 0.8)",
          },
        },
        {
          id: nanoid(),
          label: "favourite",
          count: getters.favouriteForms,
          icon: "eva-star-outline",
          color: {
            palette: "amber",
            name: "amber-6",
            rgba: "rgba(255, 193, 7, 0.8)",
          },
        },
      ];
    },
  },

  mutations: {},

  actions: {},
};
